
services:
  backend:
    build:
      context: ./backend
      dockerfile: backend-dockerfile
    container_name: backend
    ports:
      - "9567:9567"
    networks:
      - internal_network
    depends_on:
      - elasticsearch

  elasticsearch:
    image: elasticsearch:8.0.0
    container_name: elasticsearch
    build:
      context: ./elasticsearch  
      dockerfile: elasticsearch-dockerfile  
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - internal_network

networks:
  internal_network:
    driver: bridge

volumes:
  elasticsearch_data:
    driver: local
