
services:
  backend:
    build:
      context: ./backend
      dockerfile: backend-dockerfile
    container_name: backend
    ports:
      - "9567:9567"
    networks:
      - internal_network
    depends_on:
      elasticsearch:
        condition: service_healthy  # Wait until Elasticsearch is healthy

  elasticsearch:
    image: elasticsearch:8.0.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - internal_network
    healthcheck:
      test: ["CMD-SHELL", "curl -fsSL http://localhost:9200/_cluster/health || exit 1"]
      interval: 10s
      retries: 5
      start_period: 20s
      timeout: 5s

networks:
  internal_network:
    driver: bridge

volumes:
  elasticsearch_data:
    driver: local
